### ISSUE TITLE
Pre-selected items on the right-hand side

### ISSUE THREAD

**Issue by japhethmutai** [edwinhaq/yii2-listbox-dual#1]
Hey Edwin, this is a great extension. Just one clarification, how can I get items already added to the database for display on the right hand-side of the dual-listbox? That is when dealing with $model.

**Comment by vforvicious** [comment]
Hi, you can use 'selection' in widget options 
$widgetOptions['selection'] = [item1,item2...]
just the values!

**Comment by japhethmutai** [comment]
Hi, thanks for the quick response. I tried doing that but nothing happens. Is it because I am using a model as the comments below suggest?
$widgetOptions['selection'] = [1, 2]; // Ignored when model is used

**Comment by vforvicious** [comment]
When $model is used the selected items must be stored in the attribute as an array that contains items values, like in yii dropdown fields.
$model->attribute = [1,2,3,4];
In some cases i store all items in comma separated string, for example:
$model->attribute has the database value "1,2,3,4" and i need to convert it to array form use in the widget, so 
$model->attribute = explode(",",$model->attribute); 
then $model->attribute has the value [1,2,3,4];
now, if you need a default value for new records you can use:
if($model->getIsNewRecord()){
    $model->attribute = [1,2,3,4];
} 
Sorry for my english, i hope it was clear

**Comment by japhethmutai** [comment]
Wow, great! Your English is just fine. This got it working. Thank you so much.
